coverage:
  fixes:
  - /srv/src/tree-model::
  ignore:
  - .*/cppformat/.*
  - .*/QtAwesome/.*
  - .*/Catch/.*
  - .*/libgrammar/.*
  - .*/libixxx/.*
  - .*/libixxxutil/.*
  - .*/libxxxml/.*
  - .*/libxfsx/.*
